### ISSUE TITLE
Errores en Posters de Proyectos

### ISSUE THREAD

**Issue by rogelio1965** [CIMB-TEC/WebSite#29]
Proyectos/ExoDUX/Agosto 2018
- Metodología para Al Evaluación de experiencia del usuario
- Nombre actual: “Metodología para Al Evaluación de experiencia del usuario” 
    Nombre correcto: Metodología para la Evaluación de experiencia del usuario

- El link del poster manda error de “Not found”  (tanto español como inglés)

**Comment by rogelio1965** [comment]
Check multiple 404's

**Comment by Mauville** [comment]
r
