### ISSUE TITLE
Correcciones en Equipo de Investigación

### ISSUE THREAD

**Issue by rogelio1965** [CIMB-TEC/WebSite#31]
Equipo de investigación:

Directores
Dr. Rogelio Bustamante
El mail al que direcciona aun tiene la terminación “@itesm.mx”, se debe cambiar por “@tec.mx”
Dr. Arturo Molina
El mail no conecta a ninguna dirección. Mail: armolina@tec.mx

Colaboradores
Quitar a Rolando Bautista, el es encargado de proyecto.

Encargados de Proyecto
Javier izquierdo
El mail al que direcciona aun tiene la terminación “@itesm.mx”, se debe cambiar por “@tec.mx”
Sergio Alberto
Cambiar mail actual (a01215228@itesm.mx) por nuevo mail oficial: snavarro.tuch@tec.mx
Ariel Alejandro
Cambiar mail actual (ariel.lopag@gmail.com) por nuevo mail oficial: ariel.lopag@tec.mx
Rolando Bautista
Falta contacto. Mail oficial: rolando.bautista@tec.mx

Agradecimientos
Profesores
José Luis Pablos Hach es profesor y Mtro., aun no tiene el grado de Dr.
Silvia Covarrubias es profesor y Mtra., aun no tiene el grado de Dr.

**Comment by Mauville** [comment]
Problema con rolando
