### ISSUE TITLE
[BUG] Spellcheck de la traducción al inglés. 

### ISSUE THREAD

**Issue by Mauville** [CIMB-TEC/WebSite#40]
In general, the english version of the site has a lot of misspellings and grammar mistakes. Using a website grammar checker, search and correct mistakes

**Comment by Mauville** [comment]
You can use:
https://www.online-spellcheck.com/spell-check-url

https://typosaur.us/

**Comment by rogelio1965** [comment]
Acustic Agriculture

**Comment by Mauville** [comment]
Thanks!
